### ISSUE TITLE
Add ability to pass a comma delimited list of patch ids to rr

### ISSUE THREAD

**Issue by chillbrodev** [uptech/git-ps#60]
If there are multiple patches that are independent, the `rr` command should be able to accept a list of comma separated patch ids.

Example:
`git ps rr 0, 1, 2, 3`

**Comment by ctsstc** [comment]
I swore there was already an issue open for this, or talk of it somewhere. It must have only been in DMs with @drewdeponte The initial recommendation I was given was to reorder commits so they are grouped, thus you can do a range. That may be why I never went about opening an issue around this.

I feel like there may be some related talk in #35 in terms of adding additional related patches during PR, and the talk of "sub stacks" or I forget the other word going around for them right now.

I think there is definitely value in this feature. Some details may need to be hashed out around the implementation of this, although cherry picking the given indexes seems straightforward enough (if the segmented index relies on previous patches not included/conflicts it should show up).

Off topic and probably sufficient for another ticket: It would be interesting for an optimization where we could keep the branch around, and just cherry pick additions on top of the working branch/substack.

**Comment by drewdeponte** [comment]
So the reason that `git ps rr <start-patch-index>-<end-patch-index>` exists is to support the concept of requesting review of a "Patch Series". In Patch Stack workflows a "Patch Series" is a contiguous series of patches.

I seriously question the need for being able to `git ps rr 0, 1, 3, 5, 7` where they aren't contiguous and I would want to heavly review the actual use case for it.

If you are looking to just request review for a contiguous series of patches just use `git ps rr <start-patch-index>-<end-patch-index>`. Use the `git-ps` help system for further details.

If your situation isn't contiguous and you want to request review of them together. They most likely should be reordered to be contiguous as why else would you be requesting review of them in a contiguous fashion if they aren't contiguous in nature. So, just reorder your patches to be contiguous and use `git ps rr <start-patch-index>-<end-patch-index>`.

Given the above I am going to close this issue. If you still feel this needs further details please feel free to open it with more context.

**Comment by RyanHedges** [comment]
I read this as a way to make several different review requests with one command, but I could be wrong.

```
$ git-ps rr 0, 2
```

Is equivalent to...

```
$ git-ps rr 0
$ git-ps rr 2
```

**Comment by drewdeponte** [comment]
Ah interesting... I think that is an anti-pattern in my mind also. Because generally it means you are holding on to patches and not requesting review of them as soon as you could.

**Comment by chillbrodev** [comment]
Hedges is right that was the goal. I see why you think it is an anti-pattern but it is more common to stack a few patches then RR at the end since you retain the mental flow zone of coding. 

I see it as a time waste to RR each thing, because you may not always get a review right away which then effectively blocks your forward progress. Stack a few patches that dont require each other, push em all up and then wait for a review. 

Difference of opinion.

**Comment by RyanHedges** [comment]
I find myself someplace in the middle of @drewdeponte and @chillbrodev. I tend to make stupidly small changes and make rr as I finish them. These are situations where I have _high_ confidence in my changes and how they effect the system and their use. On the other hand I sometimes am building a feature outside-in, and it isn't until I've completed the feature, done some refactoring, experimentation, and feature testing, that I discover the appropriate interfaces, gain the confidence in my changes, split them up into my patches in a logical order in my stack, and then proceed to make a request for the 3 or 4 patches. So I essentially find myself doing both.

I can see how a change like could be helpful for some workflows, but I also haven't been bothered by running `git-ps rr` multiple times to try to fix it (i.e. running `$ git-ps rr 0 & git-ps rr 2` as a solution using the previous example).

**Comment by chillbrodev** [comment]
I'd say its a worthy enhancement to add since chaining them as @RyanHedges suggests is worthless typing. lol
