### ISSUE TITLE
Co-authored-by needs to come after the ps-id

### ISSUE THREAD

**Issue by ctsstc** [uptech/git-ps#61]
It seems that Github requires the co-authors to be at the end of the commit message to properly attribute the co-authors.

For example, in the image below I did the initial commit message, then I went back and reordered the commit message to have the `co-authored` after the `ps-id` which then seems to display the co-author in the UI (his profile icon shows up). I did not dig in to see if the commit counted for either of the two ways.

![image](https://user-images.githubusercontent.com/416814/150592849-487cc6ea-dcc0-4e7d-9b5c-d3a29c66b63d.png)

**Comment by drewdeponte** [comment]
This seems crappy of GitHub. There are a number of additional tags that git natively supports in the commit message similar to how we use ps-id.

I don't know how much I care to cater to GitHub for this when there are numerous tags like this and the order shouldn't matter.

GitHub should just fix their git commit processing logic.

**Comment by ctsstc** [comment]
Yep seems to be a Github thing TBH.

Seems there are many "Trailers" that are loosely defined.
- https://git.wiki.kernel.org/index.php/CommitMessageConventions#:~:text=git%20mailing%20list-,Trailers,-Some%20projects%20or
  - via:  https://stackoverflow.com/questions/7442112/how-to-attribute-a-single-commit-to-multiple-developers
